import { prisma } from "../lib/prisma";
import { subDays, startOfDay, endOfDay, format } from "date-fns";
import PDFDocument from "pdfkit";
import { Resend } from "resend";
import logger from "../lib/logger";

const resend = new Resend(process.env.RESEND_API_KEY);

export const generateWeeklySummary = async () => {
  const today = new Date();
  const lastWeek = subDays(today, 7);
  const start = startOfDay(lastWeek);
  const end = endOfDay(today);

  try {
    // 1. Fetch Data
    const [issues, serverLogs, checklistResponses] = await Promise.all([
      prisma.issue.findMany({
        where: { createdAt: { gte: start, lte: end } },
        include: { reporter: { select: { name: true } } }
      }),
      (prisma as any).serverRoomLog.findMany({
        where: { createdAt: { gte: start, lte: end } }
      }),
      prisma.checklistResponse.findMany({
        where: { createdAt: { gte: start, lte: end } },
        include: { checklistItem: true, user: { select: { name: true } } }
      })
    ]);

    // 2. Aggregate Stats
    const totalIssues = issues.length;
    const resolvedIssues = issues.filter(i => i.status === "RESOLVED").length;
    const criticalIssues = issues.filter(i => i.priority === "CRITICAL").length;
    const serverEntries = serverLogs.length;

    // 3. Create PDF
    const doc = new PDFDocument({ margin: 50 });
    const chunks: any[] = [];

    doc.on("data", (chunk) => chunks.push(chunk));

    return new Promise<Buffer>((resolve, reject) => {
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", reject);

      // --- PDF Header ---
      doc.fillColor("#004d40").fontSize(24).text("Khyber IT Operations Portal", { align: "center" });
      doc.fontSize(16).text("Weekly Summary Report", { align: "center" });
      doc.moveDown();
      doc.fillColor("#666").fontSize(10).text(`Period: ${format(start, "PPP")} - ${format(end, "PPP")}`, { align: "center" });
      doc.moveDown(2);

      // --- Executive Summary ---
      doc.fillColor("#000").fontSize(14).text("Executive Summary", { underline: true });
      doc.moveDown();
      doc.fontSize(12);
      doc.text(`• Total Incidents Logged: ${totalIssues}`);
      doc.text(`• Issues Resolved: ${resolvedIssues}`);
      doc.text(`• Critical Alerts: ${criticalIssues}`);
      doc.text(`• Server Room Entries: ${serverEntries}`);
      doc.moveDown(2);

      // --- Issues Table ---
      doc.fontSize(14).text("Recent Issues Tracker", { underline: true });
      doc.moveDown();
      issues.slice(0, 10).forEach(issue => {
        doc.fontSize(10).text(`[${issue.priority}] ${issue.title} - ${issue.status}`, { indent: 20 });
        doc.fillColor("#666").text(`Reported by: ${issue.reporter.name}`, { indent: 40 });
        doc.moveDown(0.5);
        doc.fillColor("#000");
      });
      if (issues.length > 10) doc.text(`... and ${issues.length - 10} more items.`, { indent: 20 });
      doc.moveDown(2);

      // --- Server Room Log ---
      doc.fontSize(14).text("Server Room Access Log", { underline: true });
      doc.moveDown();
      serverLogs.slice(0, 10).forEach((log: any) => {
        doc.fontSize(10).text(`${format(new Date(log.entryDate), "PP")} ${log.entryTime} - ${log.userName}`, { indent: 20 });
        doc.fillColor("#666").text(`Reason: ${log.reason}`, { indent: 40 });
        doc.moveDown(0.5);
        doc.fillColor("#000");
      });
      doc.moveDown(2);

      // --- Footer ---
      doc.fontSize(8).fillColor("#999").text("Generated automatically by Khyber IT Portal", { align: "center", bottom: 50 });

      doc.end();
    });
  } catch (error) {
    logger.error({ error }, "Failed to generate weekly summary");
    throw error;
  }
};

export const sendWeeklyReportEmail = async (pdfBuffer: Buffer) => {
  const managerEmail = process.env.MANAGER_EMAIL || "itkhy@example.com";
  
  try {
    const { data, error } = await resend.emails.send({
      from: "Khyber IT Portal <onboarding@resend.dev>",
      to: [managerEmail],
      subject: `Weekly IT Operations Report - ${format(new Date(), "PP")}`,
      html: `
        <div style="font-family: sans-serif; padding: 20px; color: #333;">
          <h2 style="color: #004d40;">Weekly Summary Report</h2>
          <p>Hello Manager,</p>
          <p>Please find attached the weekly IT operations summary for the Khyber Resort IT Department.</p>
          <hr style="border: 0; border-top: 1px solid #eee; margin: 20px 0;" />
          <p style="font-size: 12px; color: #666;">This is an automated report generated by the Khyber IT Operations Portal.</p>
        </div>
      `,
      attachments: [
        {
          filename: `Weekly_Report_${format(new Date(), "yyyy-MM-dd")}.pdf`,
          content: pdfBuffer,
        },
      ],
    });

    if (error) {
      logger.error({ error }, "Failed to send weekly report email");
      return { success: false, error };
    }

    return { success: true, data };
  } catch (error) {
    logger.error({ error }, "Unexpected error sending weekly report");
    return { success: false, error };
  }
};
